"""keep one daily session per user

Revision ID: 1d951a2a7200
Revises: 34c1fff6f6db
Create Date: 2026-09-02 17:27:27.810905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d951a2a7200'
down_revision: Union[str, Sequence[str], None] = '34c1fff6f6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_game_sessions_user_challenge', 'game_sessions', ['user_id', 'challenge_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_game_sessions_user_challenge', 'game_sessions', type_='unique')
    # ### end Alembic commands ###
