"""create infinite game tables

Revision ID: 242dd9e4e912
Revises: 3ddc1a41b6f1
Create Date: 2026-08-25 18:07:58.831462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242dd9e4e912'
down_revision: Union[str, Sequence[str], None] = '3ddc1a41b6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infinite_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infinite_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['infinite_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'cycle_number', 'song_id', name='uq_infinite_cycle_song'),
    sa.UniqueConstraint('run_id', 'round_number', name='uq_infinite_run_round_number')
    )
    op.create_index(op.f('ix_infinite_rounds_run_id'), 'infinite_rounds', ['run_id'], unique=False)
    op.create_index(op.f('ix_infinite_rounds_song_id'), 'infinite_rounds', ['song_id'], unique=False)
    op.create_table('infinite_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['infinite_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'attempt_number', name='uq_infinite_round_attempt_number')
    )
    op.create_index(op.f('ix_infinite_attempts_round_id'), 'infinite_attempts', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infinite_attempts_round_id'), table_name='infinite_attempts')
    op.drop_table('infinite_attempts')
    op.drop_index(op.f('ix_infinite_rounds_song_id'), table_name='infinite_rounds')
    op.drop_index(op.f('ix_infinite_rounds_run_id'), table_name='infinite_rounds')
    op.drop_table('infinite_rounds')
    op.drop_table('infinite_runs')
    # ### end Alembic commands ###
