"""link game sessions to users

Revision ID: 34c1fff6f6db
Revises: 1ad3e6305581
Create Date: 2026-09-01 20:11:58.710527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c1fff6f6db'
down_revision: Union[str, Sequence[str], None] = '1ad3e6305581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_foreign_key("fk_game_sessions_user_id", 'game_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('infinite_runs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_infinite_runs_user_id'), 'infinite_runs', ['user_id'], unique=False)
    op.create_foreign_key("fk_infinite_runs_user_id", 'infinite_runs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'infinite_runs', type_='foreignkey')
    op.drop_index(op.f('ix_infinite_runs_user_id'), table_name='infinite_runs')
    op.drop_column('infinite_runs', 'user_id')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_column('game_sessions', 'user_id')
    # ### end Alembic commands ###
