"""create songs and aliases

Revision ID: 46909fbd2a80
Revises: e88dd448f315
Create Date: 2026-08-19 18:33:59.510945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46909fbd2a80'
down_revision: Union[str, Sequence[str], None] = 'e88dd448f315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_songs_chapter'), 'songs', ['chapter'], unique=False)
    op.create_table('song_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('song_id', 'alias', name='uq_song_alias')
    )
    op.create_index(op.f('ix_song_aliases_song_id'), 'song_aliases', ['song_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_aliases_song_id'), table_name='song_aliases')
    op.drop_table('song_aliases')
    op.drop_index(op.f('ix_songs_chapter'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
