"""add rate limit counters

Revision ID: c4006e09b7b6
Revises: 6a5b33079999
Create Date: 2026-09-14 18:05:16.648596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4006e09b7b6'
down_revision: Union[str, Sequence[str], None] = '6a5b33079999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_rate_limits_attempts_nonnegative'),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_index(op.f('ix_rate_limits_expires_at'), 'rate_limits', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limits_expires_at'), table_name='rate_limits')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
