"""add guest game token hashes

Revision ID: f7d1347a1b33
Revises: c4006e09b7b6
Create Date: 2026-09-29 18:52:38.938427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d1347a1b33'
down_revision: Union[str, Sequence[str], None] = 'c4006e09b7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('guest_token_hash', sa.String(length=64), nullable=True))
    op.add_column('infinite_runs', sa.Column('guest_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infinite_runs', 'guest_token_hash')
    op.drop_column('game_sessions', 'guest_token_hash')
    # ### end Alembic commands ###
